[project]
name = "assign2-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ale-py>=0.10.1",
    "gymnasium>=1.0.0",
    "tinygrad>=0.10.1",
]
